// Code generated by go-swagger; DO NOT EDIT.

package crypto

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// CreateVaultOKCode is the HTTP code returned for type CreateVaultOK
const CreateVaultOKCode int = 200

/*CreateVaultOK Create vault succeeded

swagger:response createVaultOK
*/
type CreateVaultOK struct {

	/*
	  In: Body
	*/
	Payload string `json:"body,omitempty"`
}

// NewCreateVaultOK creates CreateVaultOK with default headers values
func NewCreateVaultOK() *CreateVaultOK {

	return &CreateVaultOK{}
}

// WithPayload adds the payload to the create vault o k response
func (o *CreateVaultOK) WithPayload(payload string) *CreateVaultOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the create vault o k response
func (o *CreateVaultOK) SetPayload(payload string) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *CreateVaultOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	payload := o.Payload
	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}
}

// CreateVaultBadRequestCode is the HTTP code returned for type CreateVaultBadRequest
const CreateVaultBadRequestCode int = 400

/*CreateVaultBadRequest create vault bad request

swagger:response createVaultBadRequest
*/
type CreateVaultBadRequest struct {

	/*
	  In: Body
	*/
	Payload *CreateVaultBadRequestBody `json:"body,omitempty"`
}

// NewCreateVaultBadRequest creates CreateVaultBadRequest with default headers values
func NewCreateVaultBadRequest() *CreateVaultBadRequest {

	return &CreateVaultBadRequest{}
}

// WithPayload adds the payload to the create vault bad request response
func (o *CreateVaultBadRequest) WithPayload(payload *CreateVaultBadRequestBody) *CreateVaultBadRequest {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the create vault bad request response
func (o *CreateVaultBadRequest) SetPayload(payload *CreateVaultBadRequestBody) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *CreateVaultBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(400)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// CreateVaultUnauthorizedCode is the HTTP code returned for type CreateVaultUnauthorized
const CreateVaultUnauthorizedCode int = 401

/*CreateVaultUnauthorized create vault unauthorized

swagger:response createVaultUnauthorized
*/
type CreateVaultUnauthorized struct {

	/*
	  In: Body
	*/
	Payload interface{} `json:"body,omitempty"`
}

// NewCreateVaultUnauthorized creates CreateVaultUnauthorized with default headers values
func NewCreateVaultUnauthorized() *CreateVaultUnauthorized {

	return &CreateVaultUnauthorized{}
}

// WithPayload adds the payload to the create vault unauthorized response
func (o *CreateVaultUnauthorized) WithPayload(payload interface{}) *CreateVaultUnauthorized {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the create vault unauthorized response
func (o *CreateVaultUnauthorized) SetPayload(payload interface{}) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *CreateVaultUnauthorized) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(401)
	payload := o.Payload
	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}
}

// CreateVaultForbiddenCode is the HTTP code returned for type CreateVaultForbidden
const CreateVaultForbiddenCode int = 403

/*CreateVaultForbidden create vault forbidden

swagger:response createVaultForbidden
*/
type CreateVaultForbidden struct {

	/*
	  In: Body
	*/
	Payload *CreateVaultForbiddenBody `json:"body,omitempty"`
}

// NewCreateVaultForbidden creates CreateVaultForbidden with default headers values
func NewCreateVaultForbidden() *CreateVaultForbidden {

	return &CreateVaultForbidden{}
}

// WithPayload adds the payload to the create vault forbidden response
func (o *CreateVaultForbidden) WithPayload(payload *CreateVaultForbiddenBody) *CreateVaultForbidden {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the create vault forbidden response
func (o *CreateVaultForbidden) SetPayload(payload *CreateVaultForbiddenBody) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *CreateVaultForbidden) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(403)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// CreateVaultNotFoundCode is the HTTP code returned for type CreateVaultNotFound
const CreateVaultNotFoundCode int = 404

/*CreateVaultNotFound create vault not found

swagger:response createVaultNotFound
*/
type CreateVaultNotFound struct {

	/*
	  In: Body
	*/
	Payload *CreateVaultNotFoundBody `json:"body,omitempty"`
}

// NewCreateVaultNotFound creates CreateVaultNotFound with default headers values
func NewCreateVaultNotFound() *CreateVaultNotFound {

	return &CreateVaultNotFound{}
}

// WithPayload adds the payload to the create vault not found response
func (o *CreateVaultNotFound) WithPayload(payload *CreateVaultNotFoundBody) *CreateVaultNotFound {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the create vault not found response
func (o *CreateVaultNotFound) SetPayload(payload *CreateVaultNotFoundBody) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *CreateVaultNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(404)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// CreateVaultInternalServerErrorCode is the HTTP code returned for type CreateVaultInternalServerError
const CreateVaultInternalServerErrorCode int = 500

/*CreateVaultInternalServerError create vault internal server error

swagger:response createVaultInternalServerError
*/
type CreateVaultInternalServerError struct {

	/*
	  In: Body
	*/
	Payload interface{} `json:"body,omitempty"`
}

// NewCreateVaultInternalServerError creates CreateVaultInternalServerError with default headers values
func NewCreateVaultInternalServerError() *CreateVaultInternalServerError {

	return &CreateVaultInternalServerError{}
}

// WithPayload adds the payload to the create vault internal server error response
func (o *CreateVaultInternalServerError) WithPayload(payload interface{}) *CreateVaultInternalServerError {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the create vault internal server error response
func (o *CreateVaultInternalServerError) SetPayload(payload interface{}) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *CreateVaultInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(500)
	payload := o.Payload
	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}
}
