// Code generated by go-swagger; DO NOT EDIT.

package crypto

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"context"
	"net/http"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime/middleware"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// DecryptHandlerFunc turns a function with the right signature into a decrypt handler
type DecryptHandlerFunc func(DecryptParams) middleware.Responder

// Handle executing the request and returning a response
func (fn DecryptHandlerFunc) Handle(params DecryptParams) middleware.Responder {
	return fn(params)
}

// DecryptHandler interface for that can handle valid decrypt params
type DecryptHandler interface {
	Handle(DecryptParams) middleware.Responder
}

// NewDecrypt creates a new http.Handler for the decrypt operation
func NewDecrypt(ctx *middleware.Context, handler DecryptHandler) *Decrypt {
	return &Decrypt{Context: ctx, Handler: handler}
}

/* Decrypt swagger:route POST /crypto/decrypt Crypto decrypt

Decrypt data

*/
type Decrypt struct {
	Context *middleware.Context
	Handler DecryptHandler
}

func (o *Decrypt) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewDecryptParams()
	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}

// DecryptBadRequestBody decrypt bad request body
//
// swagger:model DecryptBadRequestBody
type DecryptBadRequestBody struct {

	// message
	// Required: true
	Message *string `json:"message"`
}

// Validate validates this decrypt bad request body
func (o *DecryptBadRequestBody) Validate(formats strfmt.Registry) error {
	var res []error

	if err := o.validateMessage(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *DecryptBadRequestBody) validateMessage(formats strfmt.Registry) error {

	if err := validate.Required("decryptBadRequest"+"."+"message", "body", o.Message); err != nil {
		return err
	}

	return nil
}

// ContextValidate validates this decrypt bad request body based on context it is used
func (o *DecryptBadRequestBody) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (o *DecryptBadRequestBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *DecryptBadRequestBody) UnmarshalBinary(b []byte) error {
	var res DecryptBadRequestBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}

// DecryptForbiddenBody decrypt forbidden body
//
// swagger:model DecryptForbiddenBody
type DecryptForbiddenBody struct {

	// message
	// Required: true
	Message *string `json:"message"`
}

// Validate validates this decrypt forbidden body
func (o *DecryptForbiddenBody) Validate(formats strfmt.Registry) error {
	var res []error

	if err := o.validateMessage(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *DecryptForbiddenBody) validateMessage(formats strfmt.Registry) error {

	if err := validate.Required("decryptForbidden"+"."+"message", "body", o.Message); err != nil {
		return err
	}

	return nil
}

// ContextValidate validates this decrypt forbidden body based on context it is used
func (o *DecryptForbiddenBody) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (o *DecryptForbiddenBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *DecryptForbiddenBody) UnmarshalBinary(b []byte) error {
	var res DecryptForbiddenBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}

// DecryptNotFoundBody decrypt not found body
//
// swagger:model DecryptNotFoundBody
type DecryptNotFoundBody struct {

	// error
	// Required: true
	Error *string `json:"error"`

	// status
	// Required: true
	Status *string `json:"status"`
}

// Validate validates this decrypt not found body
func (o *DecryptNotFoundBody) Validate(formats strfmt.Registry) error {
	var res []error

	if err := o.validateError(formats); err != nil {
		res = append(res, err)
	}

	if err := o.validateStatus(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *DecryptNotFoundBody) validateError(formats strfmt.Registry) error {

	if err := validate.Required("decryptNotFound"+"."+"error", "body", o.Error); err != nil {
		return err
	}

	return nil
}

func (o *DecryptNotFoundBody) validateStatus(formats strfmt.Registry) error {

	if err := validate.Required("decryptNotFound"+"."+"status", "body", o.Status); err != nil {
		return err
	}

	return nil
}

// ContextValidate validates this decrypt not found body based on context it is used
func (o *DecryptNotFoundBody) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (o *DecryptNotFoundBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *DecryptNotFoundBody) UnmarshalBinary(b []byte) error {
	var res DecryptNotFoundBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}
