// Code generated by go-swagger; DO NOT EDIT.

package crypto

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// DeleteVaultOKCode is the HTTP code returned for type DeleteVaultOK
const DeleteVaultOKCode int = 200

/*DeleteVaultOK Delete vault succeed

swagger:response deleteVaultOK
*/
type DeleteVaultOK struct {

	/*
	  In: Body
	*/
	Payload string `json:"body,omitempty"`
}

// NewDeleteVaultOK creates DeleteVaultOK with default headers values
func NewDeleteVaultOK() *DeleteVaultOK {

	return &DeleteVaultOK{}
}

// WithPayload adds the payload to the delete vault o k response
func (o *DeleteVaultOK) WithPayload(payload string) *DeleteVaultOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the delete vault o k response
func (o *DeleteVaultOK) SetPayload(payload string) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *DeleteVaultOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	payload := o.Payload
	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}
}

// DeleteVaultBadRequestCode is the HTTP code returned for type DeleteVaultBadRequest
const DeleteVaultBadRequestCode int = 400

/*DeleteVaultBadRequest delete vault bad request

swagger:response deleteVaultBadRequest
*/
type DeleteVaultBadRequest struct {

	/*
	  In: Body
	*/
	Payload *DeleteVaultBadRequestBody `json:"body,omitempty"`
}

// NewDeleteVaultBadRequest creates DeleteVaultBadRequest with default headers values
func NewDeleteVaultBadRequest() *DeleteVaultBadRequest {

	return &DeleteVaultBadRequest{}
}

// WithPayload adds the payload to the delete vault bad request response
func (o *DeleteVaultBadRequest) WithPayload(payload *DeleteVaultBadRequestBody) *DeleteVaultBadRequest {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the delete vault bad request response
func (o *DeleteVaultBadRequest) SetPayload(payload *DeleteVaultBadRequestBody) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *DeleteVaultBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(400)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// DeleteVaultUnauthorizedCode is the HTTP code returned for type DeleteVaultUnauthorized
const DeleteVaultUnauthorizedCode int = 401

/*DeleteVaultUnauthorized delete vault unauthorized

swagger:response deleteVaultUnauthorized
*/
type DeleteVaultUnauthorized struct {

	/*
	  In: Body
	*/
	Payload interface{} `json:"body,omitempty"`
}

// NewDeleteVaultUnauthorized creates DeleteVaultUnauthorized with default headers values
func NewDeleteVaultUnauthorized() *DeleteVaultUnauthorized {

	return &DeleteVaultUnauthorized{}
}

// WithPayload adds the payload to the delete vault unauthorized response
func (o *DeleteVaultUnauthorized) WithPayload(payload interface{}) *DeleteVaultUnauthorized {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the delete vault unauthorized response
func (o *DeleteVaultUnauthorized) SetPayload(payload interface{}) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *DeleteVaultUnauthorized) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(401)
	payload := o.Payload
	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}
}

// DeleteVaultForbiddenCode is the HTTP code returned for type DeleteVaultForbidden
const DeleteVaultForbiddenCode int = 403

/*DeleteVaultForbidden delete vault forbidden

swagger:response deleteVaultForbidden
*/
type DeleteVaultForbidden struct {

	/*
	  In: Body
	*/
	Payload *DeleteVaultForbiddenBody `json:"body,omitempty"`
}

// NewDeleteVaultForbidden creates DeleteVaultForbidden with default headers values
func NewDeleteVaultForbidden() *DeleteVaultForbidden {

	return &DeleteVaultForbidden{}
}

// WithPayload adds the payload to the delete vault forbidden response
func (o *DeleteVaultForbidden) WithPayload(payload *DeleteVaultForbiddenBody) *DeleteVaultForbidden {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the delete vault forbidden response
func (o *DeleteVaultForbidden) SetPayload(payload *DeleteVaultForbiddenBody) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *DeleteVaultForbidden) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(403)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// DeleteVaultNotFoundCode is the HTTP code returned for type DeleteVaultNotFound
const DeleteVaultNotFoundCode int = 404

/*DeleteVaultNotFound delete vault not found

swagger:response deleteVaultNotFound
*/
type DeleteVaultNotFound struct {

	/*
	  In: Body
	*/
	Payload *DeleteVaultNotFoundBody `json:"body,omitempty"`
}

// NewDeleteVaultNotFound creates DeleteVaultNotFound with default headers values
func NewDeleteVaultNotFound() *DeleteVaultNotFound {

	return &DeleteVaultNotFound{}
}

// WithPayload adds the payload to the delete vault not found response
func (o *DeleteVaultNotFound) WithPayload(payload *DeleteVaultNotFoundBody) *DeleteVaultNotFound {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the delete vault not found response
func (o *DeleteVaultNotFound) SetPayload(payload *DeleteVaultNotFoundBody) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *DeleteVaultNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(404)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// DeleteVaultInternalServerErrorCode is the HTTP code returned for type DeleteVaultInternalServerError
const DeleteVaultInternalServerErrorCode int = 500

/*DeleteVaultInternalServerError delete vault internal server error

swagger:response deleteVaultInternalServerError
*/
type DeleteVaultInternalServerError struct {

	/*
	  In: Body
	*/
	Payload interface{} `json:"body,omitempty"`
}

// NewDeleteVaultInternalServerError creates DeleteVaultInternalServerError with default headers values
func NewDeleteVaultInternalServerError() *DeleteVaultInternalServerError {

	return &DeleteVaultInternalServerError{}
}

// WithPayload adds the payload to the delete vault internal server error response
func (o *DeleteVaultInternalServerError) WithPayload(payload interface{}) *DeleteVaultInternalServerError {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the delete vault internal server error response
func (o *DeleteVaultInternalServerError) SetPayload(payload interface{}) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *DeleteVaultInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(500)
	payload := o.Payload
	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}
}
