// Code generated by go-swagger; DO NOT EDIT.

package crypto

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"context"
	"net/http"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime/middleware"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// DeleteVaultHandlerFunc turns a function with the right signature into a delete vault handler
type DeleteVaultHandlerFunc func(DeleteVaultParams) middleware.Responder

// Handle executing the request and returning a response
func (fn DeleteVaultHandlerFunc) Handle(params DeleteVaultParams) middleware.Responder {
	return fn(params)
}

// DeleteVaultHandler interface for that can handle valid delete vault params
type DeleteVaultHandler interface {
	Handle(DeleteVaultParams) middleware.Responder
}

// NewDeleteVault creates a new http.Handler for the delete vault operation
func NewDeleteVault(ctx *middleware.Context, handler DeleteVaultHandler) *DeleteVault {
	return &DeleteVault{Context: ctx, Handler: handler}
}

/* DeleteVault swagger:route DELETE /crypto/vault/{name} Crypto deleteVault

Delete vault

*/
type DeleteVault struct {
	Context *middleware.Context
	Handler DeleteVaultHandler
}

func (o *DeleteVault) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewDeleteVaultParams()
	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}

// DeleteVaultBadRequestBody delete vault bad request body
//
// swagger:model DeleteVaultBadRequestBody
type DeleteVaultBadRequestBody struct {

	// message
	// Required: true
	Message *string `json:"message"`
}

// Validate validates this delete vault bad request body
func (o *DeleteVaultBadRequestBody) Validate(formats strfmt.Registry) error {
	var res []error

	if err := o.validateMessage(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *DeleteVaultBadRequestBody) validateMessage(formats strfmt.Registry) error {

	if err := validate.Required("deleteVaultBadRequest"+"."+"message", "body", o.Message); err != nil {
		return err
	}

	return nil
}

// ContextValidate validates this delete vault bad request body based on context it is used
func (o *DeleteVaultBadRequestBody) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (o *DeleteVaultBadRequestBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *DeleteVaultBadRequestBody) UnmarshalBinary(b []byte) error {
	var res DeleteVaultBadRequestBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}

// DeleteVaultForbiddenBody delete vault forbidden body
//
// swagger:model DeleteVaultForbiddenBody
type DeleteVaultForbiddenBody struct {

	// message
	// Required: true
	Message *string `json:"message"`
}

// Validate validates this delete vault forbidden body
func (o *DeleteVaultForbiddenBody) Validate(formats strfmt.Registry) error {
	var res []error

	if err := o.validateMessage(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *DeleteVaultForbiddenBody) validateMessage(formats strfmt.Registry) error {

	if err := validate.Required("deleteVaultForbidden"+"."+"message", "body", o.Message); err != nil {
		return err
	}

	return nil
}

// ContextValidate validates this delete vault forbidden body based on context it is used
func (o *DeleteVaultForbiddenBody) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (o *DeleteVaultForbiddenBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *DeleteVaultForbiddenBody) UnmarshalBinary(b []byte) error {
	var res DeleteVaultForbiddenBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}

// DeleteVaultNotFoundBody delete vault not found body
//
// swagger:model DeleteVaultNotFoundBody
type DeleteVaultNotFoundBody struct {

	// error
	// Required: true
	Error *string `json:"error"`

	// status
	// Required: true
	Status *string `json:"status"`
}

// Validate validates this delete vault not found body
func (o *DeleteVaultNotFoundBody) Validate(formats strfmt.Registry) error {
	var res []error

	if err := o.validateError(formats); err != nil {
		res = append(res, err)
	}

	if err := o.validateStatus(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *DeleteVaultNotFoundBody) validateError(formats strfmt.Registry) error {

	if err := validate.Required("deleteVaultNotFound"+"."+"error", "body", o.Error); err != nil {
		return err
	}

	return nil
}

func (o *DeleteVaultNotFoundBody) validateStatus(formats strfmt.Registry) error {

	if err := validate.Required("deleteVaultNotFound"+"."+"status", "body", o.Status); err != nil {
		return err
	}

	return nil
}

// ContextValidate validates this delete vault not found body based on context it is used
func (o *DeleteVaultNotFoundBody) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (o *DeleteVaultNotFoundBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *DeleteVaultNotFoundBody) UnmarshalBinary(b []byte) error {
	var res DeleteVaultNotFoundBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}
