// Code generated by go-swagger; DO NOT EDIT.

package crypto

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"context"
	"net/http"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime/middleware"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// EncryptHandlerFunc turns a function with the right signature into a encrypt handler
type EncryptHandlerFunc func(EncryptParams) middleware.Responder

// Handle executing the request and returning a response
func (fn EncryptHandlerFunc) Handle(params EncryptParams) middleware.Responder {
	return fn(params)
}

// EncryptHandler interface for that can handle valid encrypt params
type EncryptHandler interface {
	Handle(EncryptParams) middleware.Responder
}

// NewEncrypt creates a new http.Handler for the encrypt operation
func NewEncrypt(ctx *middleware.Context, handler EncryptHandler) *Encrypt {
	return &Encrypt{Context: ctx, Handler: handler}
}

/* Encrypt swagger:route POST /crypto/encrypt Crypto encrypt

Encrypt data

*/
type Encrypt struct {
	Context *middleware.Context
	Handler EncryptHandler
}

func (o *Encrypt) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewEncryptParams()
	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}

// EncryptBadRequestBody encrypt bad request body
//
// swagger:model EncryptBadRequestBody
type EncryptBadRequestBody struct {

	// message
	// Required: true
	Message *string `json:"message"`
}

// Validate validates this encrypt bad request body
func (o *EncryptBadRequestBody) Validate(formats strfmt.Registry) error {
	var res []error

	if err := o.validateMessage(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *EncryptBadRequestBody) validateMessage(formats strfmt.Registry) error {

	if err := validate.Required("encryptBadRequest"+"."+"message", "body", o.Message); err != nil {
		return err
	}

	return nil
}

// ContextValidate validates this encrypt bad request body based on context it is used
func (o *EncryptBadRequestBody) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (o *EncryptBadRequestBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *EncryptBadRequestBody) UnmarshalBinary(b []byte) error {
	var res EncryptBadRequestBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}

// EncryptForbiddenBody encrypt forbidden body
//
// swagger:model EncryptForbiddenBody
type EncryptForbiddenBody struct {

	// message
	// Required: true
	Message *string `json:"message"`
}

// Validate validates this encrypt forbidden body
func (o *EncryptForbiddenBody) Validate(formats strfmt.Registry) error {
	var res []error

	if err := o.validateMessage(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *EncryptForbiddenBody) validateMessage(formats strfmt.Registry) error {

	if err := validate.Required("encryptForbidden"+"."+"message", "body", o.Message); err != nil {
		return err
	}

	return nil
}

// ContextValidate validates this encrypt forbidden body based on context it is used
func (o *EncryptForbiddenBody) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (o *EncryptForbiddenBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *EncryptForbiddenBody) UnmarshalBinary(b []byte) error {
	var res EncryptForbiddenBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}

// EncryptNotFoundBody encrypt not found body
//
// swagger:model EncryptNotFoundBody
type EncryptNotFoundBody struct {

	// error
	// Required: true
	Error *string `json:"error"`

	// status
	// Required: true
	Status *string `json:"status"`
}

// Validate validates this encrypt not found body
func (o *EncryptNotFoundBody) Validate(formats strfmt.Registry) error {
	var res []error

	if err := o.validateError(formats); err != nil {
		res = append(res, err)
	}

	if err := o.validateStatus(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *EncryptNotFoundBody) validateError(formats strfmt.Registry) error {

	if err := validate.Required("encryptNotFound"+"."+"error", "body", o.Error); err != nil {
		return err
	}

	return nil
}

func (o *EncryptNotFoundBody) validateStatus(formats strfmt.Registry) error {

	if err := validate.Required("encryptNotFound"+"."+"status", "body", o.Status); err != nil {
		return err
	}

	return nil
}

// ContextValidate validates this encrypt not found body based on context it is used
func (o *EncryptNotFoundBody) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (o *EncryptNotFoundBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *EncryptNotFoundBody) UnmarshalBinary(b []byte) error {
	var res EncryptNotFoundBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}
