// Code generated by go-swagger; DO NOT EDIT.

package crypto

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"context"
	"net/http"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime/middleware"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// ListVaultsHandlerFunc turns a function with the right signature into a list vaults handler
type ListVaultsHandlerFunc func(ListVaultsParams) middleware.Responder

// Handle executing the request and returning a response
func (fn ListVaultsHandlerFunc) Handle(params ListVaultsParams) middleware.Responder {
	return fn(params)
}

// ListVaultsHandler interface for that can handle valid list vaults params
type ListVaultsHandler interface {
	Handle(ListVaultsParams) middleware.Responder
}

// NewListVaults creates a new http.Handler for the list vaults operation
func NewListVaults(ctx *middleware.Context, handler ListVaultsHandler) *ListVaults {
	return &ListVaults{Context: ctx, Handler: handler}
}

/* ListVaults swagger:route GET /crypto/vaults Crypto listVaults

List vaults

*/
type ListVaults struct {
	Context *middleware.Context
	Handler ListVaultsHandler
}

func (o *ListVaults) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewListVaultsParams()
	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}

// ListVaultsBadRequestBody list vaults bad request body
//
// swagger:model ListVaultsBadRequestBody
type ListVaultsBadRequestBody struct {

	// message
	// Required: true
	Message *string `json:"message"`
}

// Validate validates this list vaults bad request body
func (o *ListVaultsBadRequestBody) Validate(formats strfmt.Registry) error {
	var res []error

	if err := o.validateMessage(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *ListVaultsBadRequestBody) validateMessage(formats strfmt.Registry) error {

	if err := validate.Required("listVaultsBadRequest"+"."+"message", "body", o.Message); err != nil {
		return err
	}

	return nil
}

// ContextValidate validates this list vaults bad request body based on context it is used
func (o *ListVaultsBadRequestBody) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (o *ListVaultsBadRequestBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *ListVaultsBadRequestBody) UnmarshalBinary(b []byte) error {
	var res ListVaultsBadRequestBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}

// ListVaultsForbiddenBody list vaults forbidden body
//
// swagger:model ListVaultsForbiddenBody
type ListVaultsForbiddenBody struct {

	// message
	// Required: true
	Message *string `json:"message"`
}

// Validate validates this list vaults forbidden body
func (o *ListVaultsForbiddenBody) Validate(formats strfmt.Registry) error {
	var res []error

	if err := o.validateMessage(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *ListVaultsForbiddenBody) validateMessage(formats strfmt.Registry) error {

	if err := validate.Required("listVaultsForbidden"+"."+"message", "body", o.Message); err != nil {
		return err
	}

	return nil
}

// ContextValidate validates this list vaults forbidden body based on context it is used
func (o *ListVaultsForbiddenBody) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (o *ListVaultsForbiddenBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *ListVaultsForbiddenBody) UnmarshalBinary(b []byte) error {
	var res ListVaultsForbiddenBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}

// ListVaultsNotFoundBody list vaults not found body
//
// swagger:model ListVaultsNotFoundBody
type ListVaultsNotFoundBody struct {

	// error
	// Required: true
	Error *string `json:"error"`

	// status
	// Required: true
	Status *string `json:"status"`
}

// Validate validates this list vaults not found body
func (o *ListVaultsNotFoundBody) Validate(formats strfmt.Registry) error {
	var res []error

	if err := o.validateError(formats); err != nil {
		res = append(res, err)
	}

	if err := o.validateStatus(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *ListVaultsNotFoundBody) validateError(formats strfmt.Registry) error {

	if err := validate.Required("listVaultsNotFound"+"."+"error", "body", o.Error); err != nil {
		return err
	}

	return nil
}

func (o *ListVaultsNotFoundBody) validateStatus(formats strfmt.Registry) error {

	if err := validate.Required("listVaultsNotFound"+"."+"status", "body", o.Status); err != nil {
		return err
	}

	return nil
}

// ContextValidate validates this list vaults not found body based on context it is used
func (o *ListVaultsNotFoundBody) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (o *ListVaultsNotFoundBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *ListVaultsNotFoundBody) UnmarshalBinary(b []byte) error {
	var res ListVaultsNotFoundBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}
