// Code generated by go-swagger; DO NOT EDIT.

package crypto

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// ListVaultsOKCode is the HTTP code returned for type ListVaultsOK
const ListVaultsOKCode int = 200

/*ListVaultsOK Get vaults succeed

swagger:response listVaultsOK
*/
type ListVaultsOK struct {

	/*
	  In: Body
	*/
	Payload []string `json:"body,omitempty"`
}

// NewListVaultsOK creates ListVaultsOK with default headers values
func NewListVaultsOK() *ListVaultsOK {

	return &ListVaultsOK{}
}

// WithPayload adds the payload to the list vaults o k response
func (o *ListVaultsOK) WithPayload(payload []string) *ListVaultsOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the list vaults o k response
func (o *ListVaultsOK) SetPayload(payload []string) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *ListVaultsOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	payload := o.Payload
	if payload == nil {
		// return empty array
		payload = make([]string, 0, 50)
	}

	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}
}

// ListVaultsBadRequestCode is the HTTP code returned for type ListVaultsBadRequest
const ListVaultsBadRequestCode int = 400

/*ListVaultsBadRequest list vaults bad request

swagger:response listVaultsBadRequest
*/
type ListVaultsBadRequest struct {

	/*
	  In: Body
	*/
	Payload *ListVaultsBadRequestBody `json:"body,omitempty"`
}

// NewListVaultsBadRequest creates ListVaultsBadRequest with default headers values
func NewListVaultsBadRequest() *ListVaultsBadRequest {

	return &ListVaultsBadRequest{}
}

// WithPayload adds the payload to the list vaults bad request response
func (o *ListVaultsBadRequest) WithPayload(payload *ListVaultsBadRequestBody) *ListVaultsBadRequest {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the list vaults bad request response
func (o *ListVaultsBadRequest) SetPayload(payload *ListVaultsBadRequestBody) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *ListVaultsBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(400)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// ListVaultsUnauthorizedCode is the HTTP code returned for type ListVaultsUnauthorized
const ListVaultsUnauthorizedCode int = 401

/*ListVaultsUnauthorized list vaults unauthorized

swagger:response listVaultsUnauthorized
*/
type ListVaultsUnauthorized struct {

	/*
	  In: Body
	*/
	Payload interface{} `json:"body,omitempty"`
}

// NewListVaultsUnauthorized creates ListVaultsUnauthorized with default headers values
func NewListVaultsUnauthorized() *ListVaultsUnauthorized {

	return &ListVaultsUnauthorized{}
}

// WithPayload adds the payload to the list vaults unauthorized response
func (o *ListVaultsUnauthorized) WithPayload(payload interface{}) *ListVaultsUnauthorized {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the list vaults unauthorized response
func (o *ListVaultsUnauthorized) SetPayload(payload interface{}) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *ListVaultsUnauthorized) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(401)
	payload := o.Payload
	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}
}

// ListVaultsForbiddenCode is the HTTP code returned for type ListVaultsForbidden
const ListVaultsForbiddenCode int = 403

/*ListVaultsForbidden list vaults forbidden

swagger:response listVaultsForbidden
*/
type ListVaultsForbidden struct {

	/*
	  In: Body
	*/
	Payload *ListVaultsForbiddenBody `json:"body,omitempty"`
}

// NewListVaultsForbidden creates ListVaultsForbidden with default headers values
func NewListVaultsForbidden() *ListVaultsForbidden {

	return &ListVaultsForbidden{}
}

// WithPayload adds the payload to the list vaults forbidden response
func (o *ListVaultsForbidden) WithPayload(payload *ListVaultsForbiddenBody) *ListVaultsForbidden {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the list vaults forbidden response
func (o *ListVaultsForbidden) SetPayload(payload *ListVaultsForbiddenBody) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *ListVaultsForbidden) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(403)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// ListVaultsNotFoundCode is the HTTP code returned for type ListVaultsNotFound
const ListVaultsNotFoundCode int = 404

/*ListVaultsNotFound list vaults not found

swagger:response listVaultsNotFound
*/
type ListVaultsNotFound struct {

	/*
	  In: Body
	*/
	Payload *ListVaultsNotFoundBody `json:"body,omitempty"`
}

// NewListVaultsNotFound creates ListVaultsNotFound with default headers values
func NewListVaultsNotFound() *ListVaultsNotFound {

	return &ListVaultsNotFound{}
}

// WithPayload adds the payload to the list vaults not found response
func (o *ListVaultsNotFound) WithPayload(payload *ListVaultsNotFoundBody) *ListVaultsNotFound {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the list vaults not found response
func (o *ListVaultsNotFound) SetPayload(payload *ListVaultsNotFoundBody) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *ListVaultsNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(404)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// ListVaultsInternalServerErrorCode is the HTTP code returned for type ListVaultsInternalServerError
const ListVaultsInternalServerErrorCode int = 500

/*ListVaultsInternalServerError list vaults internal server error

swagger:response listVaultsInternalServerError
*/
type ListVaultsInternalServerError struct {

	/*
	  In: Body
	*/
	Payload interface{} `json:"body,omitempty"`
}

// NewListVaultsInternalServerError creates ListVaultsInternalServerError with default headers values
func NewListVaultsInternalServerError() *ListVaultsInternalServerError {

	return &ListVaultsInternalServerError{}
}

// WithPayload adds the payload to the list vaults internal server error response
func (o *ListVaultsInternalServerError) WithPayload(payload interface{}) *ListVaultsInternalServerError {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the list vaults internal server error response
func (o *ListVaultsInternalServerError) SetPayload(payload interface{}) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *ListVaultsInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(500)
	payload := o.Payload
	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}
}
