// Code generated by go-swagger; DO NOT EDIT.

package crypto

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"context"
	"net/http"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime/middleware"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// QueryVaultHandlerFunc turns a function with the right signature into a query vault handler
type QueryVaultHandlerFunc func(QueryVaultParams) middleware.Responder

// Handle executing the request and returning a response
func (fn QueryVaultHandlerFunc) Handle(params QueryVaultParams) middleware.Responder {
	return fn(params)
}

// QueryVaultHandler interface for that can handle valid query vault params
type QueryVaultHandler interface {
	Handle(QueryVaultParams) middleware.Responder
}

// NewQueryVault creates a new http.Handler for the query vault operation
func NewQueryVault(ctx *middleware.Context, handler QueryVaultHandler) *QueryVault {
	return &QueryVault{Context: ctx, Handler: handler}
}

/* QueryVault swagger:route GET /crypto/vault/{name} Crypto queryVault

Query vault

*/
type QueryVault struct {
	Context *middleware.Context
	Handler QueryVaultHandler
}

func (o *QueryVault) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewQueryVaultParams()
	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}

// QueryVaultBadRequestBody query vault bad request body
//
// swagger:model QueryVaultBadRequestBody
type QueryVaultBadRequestBody struct {

	// message
	// Required: true
	Message *string `json:"message"`
}

// Validate validates this query vault bad request body
func (o *QueryVaultBadRequestBody) Validate(formats strfmt.Registry) error {
	var res []error

	if err := o.validateMessage(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *QueryVaultBadRequestBody) validateMessage(formats strfmt.Registry) error {

	if err := validate.Required("queryVaultBadRequest"+"."+"message", "body", o.Message); err != nil {
		return err
	}

	return nil
}

// ContextValidate validates this query vault bad request body based on context it is used
func (o *QueryVaultBadRequestBody) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (o *QueryVaultBadRequestBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *QueryVaultBadRequestBody) UnmarshalBinary(b []byte) error {
	var res QueryVaultBadRequestBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}

// QueryVaultForbiddenBody query vault forbidden body
//
// swagger:model QueryVaultForbiddenBody
type QueryVaultForbiddenBody struct {

	// message
	// Required: true
	Message *string `json:"message"`
}

// Validate validates this query vault forbidden body
func (o *QueryVaultForbiddenBody) Validate(formats strfmt.Registry) error {
	var res []error

	if err := o.validateMessage(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *QueryVaultForbiddenBody) validateMessage(formats strfmt.Registry) error {

	if err := validate.Required("queryVaultForbidden"+"."+"message", "body", o.Message); err != nil {
		return err
	}

	return nil
}

// ContextValidate validates this query vault forbidden body based on context it is used
func (o *QueryVaultForbiddenBody) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (o *QueryVaultForbiddenBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *QueryVaultForbiddenBody) UnmarshalBinary(b []byte) error {
	var res QueryVaultForbiddenBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}

// QueryVaultNotFoundBody query vault not found body
//
// swagger:model QueryVaultNotFoundBody
type QueryVaultNotFoundBody struct {

	// error
	// Required: true
	Error *string `json:"error"`

	// status
	// Required: true
	Status *string `json:"status"`
}

// Validate validates this query vault not found body
func (o *QueryVaultNotFoundBody) Validate(formats strfmt.Registry) error {
	var res []error

	if err := o.validateError(formats); err != nil {
		res = append(res, err)
	}

	if err := o.validateStatus(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *QueryVaultNotFoundBody) validateError(formats strfmt.Registry) error {

	if err := validate.Required("queryVaultNotFound"+"."+"error", "body", o.Error); err != nil {
		return err
	}

	return nil
}

func (o *QueryVaultNotFoundBody) validateStatus(formats strfmt.Registry) error {

	if err := validate.Required("queryVaultNotFound"+"."+"status", "body", o.Status); err != nil {
		return err
	}

	return nil
}

// ContextValidate validates this query vault not found body based on context it is used
func (o *QueryVaultNotFoundBody) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (o *QueryVaultNotFoundBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *QueryVaultNotFoundBody) UnmarshalBinary(b []byte) error {
	var res QueryVaultNotFoundBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}
