// Code generated by go-swagger; DO NOT EDIT.

package crypto

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"context"
	"net/http"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime/middleware"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// SecretEncryptHandlerFunc turns a function with the right signature into a secret encrypt handler
type SecretEncryptHandlerFunc func(SecretEncryptParams) middleware.Responder

// Handle executing the request and returning a response
func (fn SecretEncryptHandlerFunc) Handle(params SecretEncryptParams) middleware.Responder {
	return fn(params)
}

// SecretEncryptHandler interface for that can handle valid secret encrypt params
type SecretEncryptHandler interface {
	Handle(SecretEncryptParams) middleware.Responder
}

// NewSecretEncrypt creates a new http.Handler for the secret encrypt operation
func NewSecretEncrypt(ctx *middleware.Context, handler SecretEncryptHandler) *SecretEncrypt {
	return &SecretEncrypt{Context: ctx, Handler: handler}
}

/* SecretEncrypt swagger:route POST /crypto/secret/encrypt Crypto secretEncrypt

Encrypt k8s secret

*/
type SecretEncrypt struct {
	Context *middleware.Context
	Handler SecretEncryptHandler
}

func (o *SecretEncrypt) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewSecretEncryptParams()
	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}

// SecretEncryptBadRequestBody secret encrypt bad request body
//
// swagger:model SecretEncryptBadRequestBody
type SecretEncryptBadRequestBody struct {

	// message
	// Required: true
	Message *string `json:"message"`
}

// Validate validates this secret encrypt bad request body
func (o *SecretEncryptBadRequestBody) Validate(formats strfmt.Registry) error {
	var res []error

	if err := o.validateMessage(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *SecretEncryptBadRequestBody) validateMessage(formats strfmt.Registry) error {

	if err := validate.Required("secretEncryptBadRequest"+"."+"message", "body", o.Message); err != nil {
		return err
	}

	return nil
}

// ContextValidate validates this secret encrypt bad request body based on context it is used
func (o *SecretEncryptBadRequestBody) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (o *SecretEncryptBadRequestBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *SecretEncryptBadRequestBody) UnmarshalBinary(b []byte) error {
	var res SecretEncryptBadRequestBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}

// SecretEncryptForbiddenBody secret encrypt forbidden body
//
// swagger:model SecretEncryptForbiddenBody
type SecretEncryptForbiddenBody struct {

	// message
	// Required: true
	Message *string `json:"message"`
}

// Validate validates this secret encrypt forbidden body
func (o *SecretEncryptForbiddenBody) Validate(formats strfmt.Registry) error {
	var res []error

	if err := o.validateMessage(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *SecretEncryptForbiddenBody) validateMessage(formats strfmt.Registry) error {

	if err := validate.Required("secretEncryptForbidden"+"."+"message", "body", o.Message); err != nil {
		return err
	}

	return nil
}

// ContextValidate validates this secret encrypt forbidden body based on context it is used
func (o *SecretEncryptForbiddenBody) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (o *SecretEncryptForbiddenBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *SecretEncryptForbiddenBody) UnmarshalBinary(b []byte) error {
	var res SecretEncryptForbiddenBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}

// SecretEncryptNotFoundBody secret encrypt not found body
//
// swagger:model SecretEncryptNotFoundBody
type SecretEncryptNotFoundBody struct {

	// error
	// Required: true
	Error *string `json:"error"`

	// status
	// Required: true
	Status *string `json:"status"`
}

// Validate validates this secret encrypt not found body
func (o *SecretEncryptNotFoundBody) Validate(formats strfmt.Registry) error {
	var res []error

	if err := o.validateError(formats); err != nil {
		res = append(res, err)
	}

	if err := o.validateStatus(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *SecretEncryptNotFoundBody) validateError(formats strfmt.Registry) error {

	if err := validate.Required("secretEncryptNotFound"+"."+"error", "body", o.Error); err != nil {
		return err
	}

	return nil
}

func (o *SecretEncryptNotFoundBody) validateStatus(formats strfmt.Registry) error {

	if err := validate.Required("secretEncryptNotFound"+"."+"status", "body", o.Status); err != nil {
		return err
	}

	return nil
}

// ContextValidate validates this secret encrypt not found body based on context it is used
func (o *SecretEncryptNotFoundBody) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (o *SecretEncryptNotFoundBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *SecretEncryptNotFoundBody) UnmarshalBinary(b []byte) error {
	var res SecretEncryptNotFoundBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}
