// Code generated by go-swagger; DO NOT EDIT.

package crypto

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"flexagent/models"
)

// SecretDecryptOKCode is the HTTP code returned for type SecretDecryptOK
const SecretDecryptOKCode int = 200

/*SecretDecryptOK Secret decrypted

swagger:response secretDecryptOK
*/
type SecretDecryptOK struct {

	/*
	  In: Body
	*/
	Payload *models.KubeSecret `json:"body,omitempty"`
}

// NewSecretDecryptOK creates SecretDecryptOK with default headers values
func NewSecretDecryptOK() *SecretDecryptOK {

	return &SecretDecryptOK{}
}

// WithPayload adds the payload to the secret decrypt o k response
func (o *SecretDecryptOK) WithPayload(payload *models.KubeSecret) *SecretDecryptOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the secret decrypt o k response
func (o *SecretDecryptOK) SetPayload(payload *models.KubeSecret) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *SecretDecryptOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// SecretDecryptBadRequestCode is the HTTP code returned for type SecretDecryptBadRequest
const SecretDecryptBadRequestCode int = 400

/*SecretDecryptBadRequest secret decrypt bad request

swagger:response secretDecryptBadRequest
*/
type SecretDecryptBadRequest struct {

	/*
	  In: Body
	*/
	Payload *SecretDecryptBadRequestBody `json:"body,omitempty"`
}

// NewSecretDecryptBadRequest creates SecretDecryptBadRequest with default headers values
func NewSecretDecryptBadRequest() *SecretDecryptBadRequest {

	return &SecretDecryptBadRequest{}
}

// WithPayload adds the payload to the secret decrypt bad request response
func (o *SecretDecryptBadRequest) WithPayload(payload *SecretDecryptBadRequestBody) *SecretDecryptBadRequest {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the secret decrypt bad request response
func (o *SecretDecryptBadRequest) SetPayload(payload *SecretDecryptBadRequestBody) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *SecretDecryptBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(400)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// SecretDecryptUnauthorizedCode is the HTTP code returned for type SecretDecryptUnauthorized
const SecretDecryptUnauthorizedCode int = 401

/*SecretDecryptUnauthorized secret decrypt unauthorized

swagger:response secretDecryptUnauthorized
*/
type SecretDecryptUnauthorized struct {

	/*
	  In: Body
	*/
	Payload interface{} `json:"body,omitempty"`
}

// NewSecretDecryptUnauthorized creates SecretDecryptUnauthorized with default headers values
func NewSecretDecryptUnauthorized() *SecretDecryptUnauthorized {

	return &SecretDecryptUnauthorized{}
}

// WithPayload adds the payload to the secret decrypt unauthorized response
func (o *SecretDecryptUnauthorized) WithPayload(payload interface{}) *SecretDecryptUnauthorized {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the secret decrypt unauthorized response
func (o *SecretDecryptUnauthorized) SetPayload(payload interface{}) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *SecretDecryptUnauthorized) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(401)
	payload := o.Payload
	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}
}

// SecretDecryptForbiddenCode is the HTTP code returned for type SecretDecryptForbidden
const SecretDecryptForbiddenCode int = 403

/*SecretDecryptForbidden secret decrypt forbidden

swagger:response secretDecryptForbidden
*/
type SecretDecryptForbidden struct {

	/*
	  In: Body
	*/
	Payload *SecretDecryptForbiddenBody `json:"body,omitempty"`
}

// NewSecretDecryptForbidden creates SecretDecryptForbidden with default headers values
func NewSecretDecryptForbidden() *SecretDecryptForbidden {

	return &SecretDecryptForbidden{}
}

// WithPayload adds the payload to the secret decrypt forbidden response
func (o *SecretDecryptForbidden) WithPayload(payload *SecretDecryptForbiddenBody) *SecretDecryptForbidden {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the secret decrypt forbidden response
func (o *SecretDecryptForbidden) SetPayload(payload *SecretDecryptForbiddenBody) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *SecretDecryptForbidden) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(403)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// SecretDecryptNotFoundCode is the HTTP code returned for type SecretDecryptNotFound
const SecretDecryptNotFoundCode int = 404

/*SecretDecryptNotFound secret decrypt not found

swagger:response secretDecryptNotFound
*/
type SecretDecryptNotFound struct {

	/*
	  In: Body
	*/
	Payload *SecretDecryptNotFoundBody `json:"body,omitempty"`
}

// NewSecretDecryptNotFound creates SecretDecryptNotFound with default headers values
func NewSecretDecryptNotFound() *SecretDecryptNotFound {

	return &SecretDecryptNotFound{}
}

// WithPayload adds the payload to the secret decrypt not found response
func (o *SecretDecryptNotFound) WithPayload(payload *SecretDecryptNotFoundBody) *SecretDecryptNotFound {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the secret decrypt not found response
func (o *SecretDecryptNotFound) SetPayload(payload *SecretDecryptNotFoundBody) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *SecretDecryptNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(404)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// SecretDecryptInternalServerErrorCode is the HTTP code returned for type SecretDecryptInternalServerError
const SecretDecryptInternalServerErrorCode int = 500

/*SecretDecryptInternalServerError secret decrypt internal server error

swagger:response secretDecryptInternalServerError
*/
type SecretDecryptInternalServerError struct {

	/*
	  In: Body
	*/
	Payload interface{} `json:"body,omitempty"`
}

// NewSecretDecryptInternalServerError creates SecretDecryptInternalServerError with default headers values
func NewSecretDecryptInternalServerError() *SecretDecryptInternalServerError {

	return &SecretDecryptInternalServerError{}
}

// WithPayload adds the payload to the secret decrypt internal server error response
func (o *SecretDecryptInternalServerError) WithPayload(payload interface{}) *SecretDecryptInternalServerError {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the secret decrypt internal server error response
func (o *SecretDecryptInternalServerError) SetPayload(payload interface{}) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *SecretDecryptInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(500)
	payload := o.Payload
	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}
}
