// Code generated by go-swagger; DO NOT EDIT.

package agent

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"flexagent/models"
)

// HealthzOKCode is the HTTP code returned for type HealthzOK
const HealthzOKCode int = 200

/*HealthzOK Health status

swagger:response healthzOK
*/
type HealthzOK struct {

	/*
	  In: Body
	*/
	Payload *models.HealthStatus `json:"body,omitempty"`
}

// NewHealthzOK creates HealthzOK with default headers values
func NewHealthzOK() *HealthzOK {

	return &HealthzOK{}
}

// WithPayload adds the payload to the healthz o k response
func (o *HealthzOK) WithPayload(payload *models.HealthStatus) *HealthzOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the healthz o k response
func (o *HealthzOK) SetPayload(payload *models.HealthStatus) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *HealthzOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
