// Code generated by go-swagger; DO NOT EDIT.

package job

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"context"
	"net/http"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime/middleware"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// InputHandlerFunc turns a function with the right signature into a input handler
type InputHandlerFunc func(InputParams) middleware.Responder

// Handle executing the request and returning a response
func (fn InputHandlerFunc) Handle(params InputParams) middleware.Responder {
	return fn(params)
}

// InputHandler interface for that can handle valid input params
type InputHandler interface {
	Handle(InputParams) middleware.Responder
}

// NewInput creates a new http.Handler for the input operation
func NewInput(ctx *middleware.Context, handler InputHandler) *Input {
	return &Input{Context: ctx, Handler: handler}
}

/* Input swagger:route POST /jobs/{urn}/input Job input

Expect and input

*/
type Input struct {
	Context *middleware.Context
	Handler InputHandler
}

func (o *Input) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewInputParams()
	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}

// InputBadRequestBody input bad request body
//
// swagger:model InputBadRequestBody
type InputBadRequestBody struct {

	// message
	// Required: true
	Message *string `json:"message"`
}

// Validate validates this input bad request body
func (o *InputBadRequestBody) Validate(formats strfmt.Registry) error {
	var res []error

	if err := o.validateMessage(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *InputBadRequestBody) validateMessage(formats strfmt.Registry) error {

	if err := validate.Required("inputBadRequest"+"."+"message", "body", o.Message); err != nil {
		return err
	}

	return nil
}

// ContextValidate validates this input bad request body based on context it is used
func (o *InputBadRequestBody) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (o *InputBadRequestBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *InputBadRequestBody) UnmarshalBinary(b []byte) error {
	var res InputBadRequestBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}

// InputForbiddenBody input forbidden body
//
// swagger:model InputForbiddenBody
type InputForbiddenBody struct {

	// message
	// Required: true
	Message *string `json:"message"`
}

// Validate validates this input forbidden body
func (o *InputForbiddenBody) Validate(formats strfmt.Registry) error {
	var res []error

	if err := o.validateMessage(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *InputForbiddenBody) validateMessage(formats strfmt.Registry) error {

	if err := validate.Required("inputForbidden"+"."+"message", "body", o.Message); err != nil {
		return err
	}

	return nil
}

// ContextValidate validates this input forbidden body based on context it is used
func (o *InputForbiddenBody) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (o *InputForbiddenBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *InputForbiddenBody) UnmarshalBinary(b []byte) error {
	var res InputForbiddenBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}

// InputNotFoundBody input not found body
//
// swagger:model InputNotFoundBody
type InputNotFoundBody struct {

	// error
	// Required: true
	Error *string `json:"error"`

	// status
	// Required: true
	Status *string `json:"status"`
}

// Validate validates this input not found body
func (o *InputNotFoundBody) Validate(formats strfmt.Registry) error {
	var res []error

	if err := o.validateError(formats); err != nil {
		res = append(res, err)
	}

	if err := o.validateStatus(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *InputNotFoundBody) validateError(formats strfmt.Registry) error {

	if err := validate.Required("inputNotFound"+"."+"error", "body", o.Error); err != nil {
		return err
	}

	return nil
}

func (o *InputNotFoundBody) validateStatus(formats strfmt.Registry) error {

	if err := validate.Required("inputNotFound"+"."+"status", "body", o.Status); err != nil {
		return err
	}

	return nil
}

// ContextValidate validates this input not found body based on context it is used
func (o *InputNotFoundBody) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (o *InputNotFoundBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *InputNotFoundBody) UnmarshalBinary(b []byte) error {
	var res InputNotFoundBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}
