// Code generated by go-swagger; DO NOT EDIT.

package job

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"context"
	"net/http"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime/middleware"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// KillHandlerFunc turns a function with the right signature into a kill handler
type KillHandlerFunc func(KillParams) middleware.Responder

// Handle executing the request and returning a response
func (fn KillHandlerFunc) Handle(params KillParams) middleware.Responder {
	return fn(params)
}

// KillHandler interface for that can handle valid kill params
type KillHandler interface {
	Handle(KillParams) middleware.Responder
}

// NewKill creates a new http.Handler for the kill operation
func NewKill(ctx *middleware.Context, handler KillHandler) *Kill {
	return &Kill{Context: ctx, Handler: handler}
}

/* Kill swagger:route POST /jobs/{urn}/kill Job kill

Kill job

*/
type Kill struct {
	Context *middleware.Context
	Handler KillHandler
}

func (o *Kill) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewKillParams()
	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}

// KillBadRequestBody kill bad request body
//
// swagger:model KillBadRequestBody
type KillBadRequestBody struct {

	// message
	// Required: true
	Message *string `json:"message"`
}

// Validate validates this kill bad request body
func (o *KillBadRequestBody) Validate(formats strfmt.Registry) error {
	var res []error

	if err := o.validateMessage(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *KillBadRequestBody) validateMessage(formats strfmt.Registry) error {

	if err := validate.Required("killBadRequest"+"."+"message", "body", o.Message); err != nil {
		return err
	}

	return nil
}

// ContextValidate validates this kill bad request body based on context it is used
func (o *KillBadRequestBody) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (o *KillBadRequestBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *KillBadRequestBody) UnmarshalBinary(b []byte) error {
	var res KillBadRequestBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}

// KillForbiddenBody kill forbidden body
//
// swagger:model KillForbiddenBody
type KillForbiddenBody struct {

	// message
	// Required: true
	Message *string `json:"message"`
}

// Validate validates this kill forbidden body
func (o *KillForbiddenBody) Validate(formats strfmt.Registry) error {
	var res []error

	if err := o.validateMessage(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *KillForbiddenBody) validateMessage(formats strfmt.Registry) error {

	if err := validate.Required("killForbidden"+"."+"message", "body", o.Message); err != nil {
		return err
	}

	return nil
}

// ContextValidate validates this kill forbidden body based on context it is used
func (o *KillForbiddenBody) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (o *KillForbiddenBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *KillForbiddenBody) UnmarshalBinary(b []byte) error {
	var res KillForbiddenBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}

// KillNotFoundBody kill not found body
//
// swagger:model KillNotFoundBody
type KillNotFoundBody struct {

	// error
	// Required: true
	Error *string `json:"error"`

	// status
	// Required: true
	Status *string `json:"status"`
}

// Validate validates this kill not found body
func (o *KillNotFoundBody) Validate(formats strfmt.Registry) error {
	var res []error

	if err := o.validateError(formats); err != nil {
		res = append(res, err)
	}

	if err := o.validateStatus(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *KillNotFoundBody) validateError(formats strfmt.Registry) error {

	if err := validate.Required("killNotFound"+"."+"error", "body", o.Error); err != nil {
		return err
	}

	return nil
}

func (o *KillNotFoundBody) validateStatus(formats strfmt.Registry) error {

	if err := validate.Required("killNotFound"+"."+"status", "body", o.Status); err != nil {
		return err
	}

	return nil
}

// ContextValidate validates this kill not found body based on context it is used
func (o *KillNotFoundBody) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (o *KillNotFoundBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *KillNotFoundBody) UnmarshalBinary(b []byte) error {
	var res KillNotFoundBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}
