// Code generated by go-swagger; DO NOT EDIT.

// Package restapi agent
//
//  Agent framwork to perform node operations
//
//  Schemes:
//    http
//    https
//  Host: localhost
//  BasePath: /api/v1
//  Version: v1
//  Contact: Wang Yaohui<yaohuiwang@outlook.com>
//
//  Consumes:
//    - application/json
//
//  Produces:
//    - application/json
//
// swagger:meta
package restapi
