// Code generated by go-swagger; DO NOT EDIT.

package cronjob

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"io"
	"net/http"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/runtime/middleware"

	"flexagent/models"
)

// NewSubmitCronJobsParams creates a new SubmitCronJobsParams object
//
// There are no default values defined in the spec.
func NewSubmitCronJobsParams() SubmitCronJobsParams {

	return SubmitCronJobsParams{}
}

// SubmitCronJobsParams contains all the bound params for the submit cron jobs operation
// typically these are obtained from a http.Request
//
// swagger:parameters submitCronJobs
type SubmitCronJobsParams struct {

	// HTTP Request Object
	HTTPRequest *http.Request `json:"-"`

	/*Cronjobs spec
	  Required: true
	  In: body
	*/
	Spec []*models.CronJobSpec
}

// BindRequest both binds and validates a request, it assumes that complex things implement a Validatable(strfmt.Registry) error interface
// for simple values it will use straight method calls.
//
// To ensure default values, the struct must have been initialized with NewSubmitCronJobsParams() beforehand.
func (o *SubmitCronJobsParams) BindRequest(r *http.Request, route *middleware.MatchedRoute) error {
	var res []error

	o.HTTPRequest = r

	if runtime.HasBody(r) {
		defer r.Body.Close()
		var body []*models.CronJobSpec
		if err := route.Consumer.Consume(r.Body, &body); err != nil {
			if err == io.EOF {
				res = append(res, errors.Required("spec", "body", ""))
			} else {
				res = append(res, errors.NewParseError("spec", "body", "", err))
			}
		} else {

			// validate array of body objects
			for i := range body {
				if body[i] == nil {
					continue
				}
				if err := body[i].Validate(route.Formats); err != nil {
					res = append(res, err)
					break
				}
			}

			if len(res) == 0 {
				o.Spec = body
			}
		}
	} else {
		res = append(res, errors.Required("spec", "body", ""))
	}
	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
